
package com.em.itr.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ITRInvalidCertificateFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0")
public class ITRInvalidCertificateFaultException_Exception extends Exception {
    public static final long serialVersionUID = 20100811220910L;
    
    private com.em.itr.webservice.ITRInvalidCertificateFaultException itrInvalidCertificateFaultException;

    public ITRInvalidCertificateFaultException_Exception() {
        super();
    }
    
    public ITRInvalidCertificateFaultException_Exception(String message) {
        super(message);
    }
    
    public ITRInvalidCertificateFaultException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITRInvalidCertificateFaultException_Exception(String message, com.em.itr.webservice.ITRInvalidCertificateFaultException itrInvalidCertificateFaultException) {
        super(message);
        this.itrInvalidCertificateFaultException = itrInvalidCertificateFaultException;
    }

    public ITRInvalidCertificateFaultException_Exception(String message, com.em.itr.webservice.ITRInvalidCertificateFaultException itrInvalidCertificateFaultException, Throwable cause) {
        super(message, cause);
        this.itrInvalidCertificateFaultException = itrInvalidCertificateFaultException;
    }

    public com.em.itr.webservice.ITRInvalidCertificateFaultException getFaultInfo() {
        return this.itrInvalidCertificateFaultException;
    }
}
