package com.em.itr.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0", name = "ITRServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ITRServicePort {

    @WebResult(name = "DITWSResponseEle", targetNamespace = "http://incometaxindiaefiling.gov.in/ws/ds/common/v_1_0", partName = "itrStatus")
    @WebMethod(action = "http://incometaxindiaefiling.gov.in/submitITReturn")
    public DITWSResponse submitITR(
        @WebParam(partName = "authInfo", name = "DITWSAuthInfoEle", targetNamespace = "http://incometaxindiaefiling.gov.in/ws/ds/common/v_1_0")
        DITWSAuthInfo authInfo,
        @XmlJavaTypeAdapter(value = HexBinaryAdapter.class)
        @WebParam(partName = "itrXMLFile", name = "itrXMLFile", targetNamespace = "")
        byte[] itrXMLFile
    ) throws ITRBusinessServiceFaultException_Exception, ITRInvalidCertificateFaultException_Exception, ITRServiceFaultException_Exception, ITRCredentialFaultException_Exception, ITRInvalidDocFaultException_Exception, ITRFaultException_Exception;
}
