
package com.em.itr.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ITRBusinessServiceFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0")
public class ITRBusinessServiceFaultException_Exception extends Exception {
    public static final long serialVersionUID = 20100811220910L;
    
    private com.em.itr.webservice.ITRBusinessServiceFaultException itrBusinessServiceFaultException;

    public ITRBusinessServiceFaultException_Exception() {
        super();
    }
    
    public ITRBusinessServiceFaultException_Exception(String message) {
        super(message);
    }
    
    public ITRBusinessServiceFaultException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITRBusinessServiceFaultException_Exception(String message, com.em.itr.webservice.ITRBusinessServiceFaultException itrBusinessServiceFaultException) {
        super(message);
        this.itrBusinessServiceFaultException = itrBusinessServiceFaultException;
    }

    public ITRBusinessServiceFaultException_Exception(String message, com.em.itr.webservice.ITRBusinessServiceFaultException itrBusinessServiceFaultException, Throwable cause) {
        super(message, cause);
        this.itrBusinessServiceFaultException = itrBusinessServiceFaultException;
    }

    public com.em.itr.webservice.ITRBusinessServiceFaultException getFaultInfo() {
        return this.itrBusinessServiceFaultException;
    }
}
