
package com.em.itr.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ITRCredentialFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0")
public class ITRCredentialFaultException_Exception extends Exception {
    public static final long serialVersionUID = 20100811220910L;
    
    private com.em.itr.webservice.ITRCredentialFaultException itrCredentialFaultException;

    public ITRCredentialFaultException_Exception() {
        super();
    }
    
    public ITRCredentialFaultException_Exception(String message) {
        super(message);
    }
    
    public ITRCredentialFaultException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITRCredentialFaultException_Exception(String message, com.em.itr.webservice.ITRCredentialFaultException itrCredentialFaultException) {
        super(message);
        this.itrCredentialFaultException = itrCredentialFaultException;
    }

    public ITRCredentialFaultException_Exception(String message, com.em.itr.webservice.ITRCredentialFaultException itrCredentialFaultException, Throwable cause) {
        super(message, cause);
        this.itrCredentialFaultException = itrCredentialFaultException;
    }

    public com.em.itr.webservice.ITRCredentialFaultException getFaultInfo() {
        return this.itrCredentialFaultException;
    }
}
