
/*
 * 
 */

package com.em.itr.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "ITRService", 
                  wsdlLocation = "https://incometaxindiaefiling.gov.in/ditws/v_1_0/ITRServiceSoapHttpPort?wsdl",
                  targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0") 
public class ITRService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://incometaxindiaefiling.gov.in/itrservice/v_1_0", "ITRService");
    public final static QName ITRServiceSoapHttpPort = new QName("http://incometaxindiaefiling.gov.in/itrservice/v_1_0", "ITRServiceSoapHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("https://incometaxindiaefiling.gov.in/ditws/v_1_0/ITRServiceSoapHttpPort?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://incometaxindiaefiling.gov.in/ditws/v_1_0/ITRServiceSoapHttpPort?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ITRService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ITRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITRService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ITRServicePort
     */
    @WebEndpoint(name = "ITRServiceSoapHttpPort")
    public ITRServicePort getITRServiceSoapHttpPort() {
        return super.getPort(ITRServiceSoapHttpPort, ITRServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITRServicePort
     */
    @WebEndpoint(name = "ITRServiceSoapHttpPort")
    public ITRServicePort getITRServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(ITRServiceSoapHttpPort, ITRServicePort.class, features);
    }

}
