
package com.em.itr.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 11 22:09:10 IST 2010
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ITRServiceFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0")
public class ITRServiceFaultException_Exception extends Exception {
    public static final long serialVersionUID = 20100811220910L;
    
    private com.em.itr.webservice.ITRServiceFaultException itrServiceFaultException;

    public ITRServiceFaultException_Exception() {
        super();
    }
    
    public ITRServiceFaultException_Exception(String message) {
        super(message);
    }
    
    public ITRServiceFaultException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITRServiceFaultException_Exception(String message, com.em.itr.webservice.ITRServiceFaultException itrServiceFaultException) {
        super(message);
        this.itrServiceFaultException = itrServiceFaultException;
    }

    public ITRServiceFaultException_Exception(String message, com.em.itr.webservice.ITRServiceFaultException itrServiceFaultException, Throwable cause) {
        super(message, cause);
        this.itrServiceFaultException = itrServiceFaultException;
    }

    public com.em.itr.webservice.ITRServiceFaultException getFaultInfo() {
        return this.itrServiceFaultException;
    }
}
